---
engines:
  eslint:
    # Enabled in Code Climate
    enabled: false
  jacksonlinter:
    enabled: true
  phpmd:
    # Enabled in Code Climate
    enabled: false
  rubocop:
    # Not Applicable
    enabled: false
  shellcheck:
    # Enabled in Code Climate
    enabled: false
  stylelint:
    # Enabled in Code Climate
    enabled: false
  duplication:
    enabled: true
  metrics:
    enabled: true
  coverage:
    enabled: true
exclude_paths:
  - "_libs/**"
  - "**.min.css"
  - "**.custom.css"
  - "**.min.js"
  - "**.pack.js"
  - "**.custom.js"
