# eustasy Normalized Checks 2.0.0-beta

dist: trusty
sudo: required

# https://secure.php.net/supported-versions.php
language: php
php:
  - 7.3
  - 7.4

# Uncomment the following two lines if you wish to test any SQL files.
#addons:
#  mariadb: '10.1'

before_script:
  - git clone https://github.com/eustasy/normal-checks.git
  - cd normal-checks
  - git checkout b92da74ddf4b05b698e2d12ebd56e965d6749397
  - cd ../
  - npm install --silent -g npm
  # for testing JavaScript
  - npm install --silent -g acorn

script:
  - ./normal-checks/check-javascript.sh
  - ./normal-checks/check-php.sh
  - php normal-checks/check-json.php
  - php normal-checks/check-xml.php
  # Uncomment the following two lines if you wish to test any SQL files.
  #- sudo mysql -u root -e 'CREATE DATABASE IF NOT EXISTS tests_db;'
  #- sudo mysql -u root tests_db < empty/test.sql
