# eustasy Normalized Checks 2.0.0-beta

os: linux
arch: amd64
dist: focal

# https://secure.php.net/supported-versions.php
language: php
php:
  - 7.4
  - 8.0

# Uncomment the following two lines if you wish to test any SQL files.
#addons:
#  mariadb: '10.1'

before_script:
  - git clone https://github.com/eustasy/.normal.git
  - cd .normal
  - git checkout b92da74ddf4b05b698e2d12ebd56e965d6749397
  - cd ../
  - npm install --silent -g npm
  # for testing JavaScript
  - npm install --silent -g acorn

script:
  - ./.normal/check-javascript.sh
  - ./.normal/check-php.sh
  - php .normal/check-json.php
  - php .normal/check-xml.php
  # Uncomment the following two lines if you wish to test any SQL files.
  #- sudo mysql -u root -e 'CREATE DATABASE IF NOT EXISTS tests_db;'
  #- sudo mysql -u root tests_db < empty/test.sql
