# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

dist: trusty
sudo: required

language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: hhvm

before_script:
  - git clone https://github.com/eustasy/normal-checks.git
  - cd normal-checks
  - git checkout 768000d77c2818c49d8a38e66725c30aee2f281f
  - cd ../

script:
  - ./normal-checks/check-config.sh
  - ./normal-checks/check-permissions.sh
  - ./normal-checks/check-javascript.sh
  - ./normal-checks/check-css.sh
  - ./normal-checks/check-php.sh
  - php normal-checks/check-json.php
  - php normal-checks/check-xml.php

notifications:
  email:
    recipients:
      - lewisgoddard@eustasy.org
    on_success: change
    on_failure: change
