name: Normal PHP Lint
description: Lint PHP with phpstan and format-check it with php-cs-fixer.

runs:
  using: composite
  steps:
    - uses: qltysh/qlty-action/install@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0

    - name: Lint (phpstan)
      shell: bash
      run: qlty check --all --no-formatters --filter=phpstan

    - name: Format check (php-cs-fixer)
      shell: bash
      run: qlty check --all --filter=php-cs-fixer
