name: Normal JSON
description: Format-check JSON with prettier.

runs:
  using: composite
  steps:
    - uses: qltysh/qlty-action/install@c9b09987143d1e4ac955f4803c7bea742102feb5 # v2.4.0

    - name: Format check (prettier)
      shell: bash
      run: git ls-files -- '*.json' | xargs -r qlty check --filter=prettier
