# eustasy/.Normal 4.0beta10
name: "Normal: Python"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/python.yml"
      - ".qlty/configs/ruff.toml"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/python.yml"
      - ".qlty/configs/ruff.toml"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  python:
    name: Lint + format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: qltysh/qlty-action/install@dafbc1e328f1f92525f1a3916724bd5fa01498e8 # v2.2.3

      - name: Lint (ruff)
        run: qlty check --all --no-formatters --filter=ruff

      - name: Format check (ruff)
        run: qlty check --all --filter=ruff
