# eustasy/.Normal 4.0beta16
name: "Normal: XML"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.xml"
      - ".github/workflows/xml.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.xml"
      - ".github/workflows/xml.yml"

permissions:
  contents: read

jobs:
  xml:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/xml@v4
