name: Normal YAML
description: Lint YAML with yamllint.

runs:
  using: composite
  steps:
    - uses: qltysh/qlty-action/install@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0

    - name: Lint (yamllint)
      shell: bash
      run: qlty check --all --no-formatters --filter=yamllint
